apiVersion: v1
kind: ConfigMap
metadata:
  name: trino-catalog
  labels:
    app: trino
    trino-release: latest
    trino-component: catalog
data:
  tpch.properties: |
    connector.name=tpch
    tpch.splits-per-node=4
  tpcds.properties: |
    connector.name=tpcds
    tpcds.splits-per-node=4


